cabal-version: 3.4
name:          marlowe-transactions
version:       0.1.0.0
license:       Apache-2.0
build-type:    Simple
maintainer:    tomasz.rybarczyk@marlowe-lang.org
stability:     experimental
author:        paluh (aka Tomasz Rybarczyk)
synopsis:      Marlowe pure transaction builders
category:      Language
license-files:
  LICENSE
  NOTICE

source-repository head
  type:     git
  location: https://github.com/marlowe-lang/marlowe-plutus

common lang
  default-language:   Haskell2010
  default-extensions:
    BangPatterns
    BlockArguments
    ConstraintKinds
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveDataTypeable
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveLift
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    DoAndIfThenElse
    DuplicateRecordFields
    EmptyCase
    EmptyDataDeriving
    ExplicitForAll
    ExplicitNamespaces
    FlexibleContexts
    FlexibleInstances
    FunctionalDependencies
    GADTs
    GeneralizedNewtypeDeriving
    ImportQualifiedPost
    LambdaCase
    MultiParamTypeClasses
    NamedFieldPuns
    NumericUnderscores
    OverloadedRecordDot
    OverloadedStrings
    PatternSynonyms
    QuantifiedConstraints
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeFamilyDependencies
    TypeOperators
    ViewPatterns

  ghc-options:
    -Wall -Wnoncanonical-monad-instances
    -Wincomplete-uni-patterns -Wincomplete-record-updates
    -Wredundant-constraints -Widentities -Werror

library
  import:          lang
  hs-source-dirs:  src
  build-depends:
    , async
    , aeson
    , attoparsec
    , base
    , base16-aeson
    , base16 ^>=1.0
    , binary ^>=0.8.8
    , bytestring
    , cardano-api
    , cardano-binary
    , cardano-crypto-class
    , cardano-ledger-allegra
    , cardano-ledger-alonzo
    , cardano-ledger-api
    , cardano-ledger-babbage
    , cardano-ledger-binary
    , cardano-ledger-byron
    , cardano-ledger-conway
    , cardano-ledger-dijkstra
    , cardano-ledger-core
    , cardano-ledger-mary
    , cardano-ledger-shelley
    , containers
    , deepseq
    , errors
    , groups
    , hashable
    , http-media
    , keys
    , lens
    , log-base
    , marlowe-binaries ^>=0.2
    , marlowe-plutus ^>=0.2
    , microlens
    , network-uri
    , nonempty-containers
    , ouroboros-consensus
    , ouroboros-network-api
    , plutus-core ^>=1.57
    , plutus-ledger-api ^>=1.57
    , plutus-tx ^>=1.57
    , plutus-tx-plugin ^>=1.57
    , reflection
    , scientific
    , semialign
    , semigroups
    , semigroupoids
    , sop-core
    , sop-extras
    , strict-sop-core
    , text
    , these
    , time
    , transformers
    , unliftio-core
    , unordered-containers
    , variations
    , vector

  exposed-modules:
    Language.Marlowe.Runtime.Cardano.Api
    Language.Marlowe.Runtime.Cardano.Api.Kupo
    Language.Marlowe.Runtime.Cardano.Feature
    Language.Marlowe.Runtime.ChainSync.Api
    Language.Marlowe.Runtime.Core.Api
    Language.Marlowe.Runtime.Core.ScriptRegistry
    Language.Marlowe.Runtime.History.Api
    Language.Marlowe.Runtime.Plutus.V2.Api
    Language.Marlowe.Runtime.Plutus.V3.Api
    Language.Marlowe.Runtime.Transaction.Api
    Language.Marlowe.Runtime.Transaction.Builders
    Language.Marlowe.Runtime.Transaction.BuildConstraints
    Language.Marlowe.Runtime.Transaction.Constraints
    Language.Marlowe.Runtime.Transaction.Safety

library gen
  import:          lang
  hs-source-dirs:  gen
  visibility:      public
  exposed-modules:
    Language.Marlowe.Runtime.ChainSync.Gen
    Language.Marlowe.Runtime.Core.Gen
    Language.Marlowe.Runtime.History.Gen
    Language.Marlowe.Runtime.Transaction.Gen

  build-depends:
    , base >=4.9 && <5
    , bytestring >=0.10.12 && <0.12
    , cardano-api ^>=10.23
    , cardano-api-gen ^>=10.2
    , cardano-protocol-tpraos
    , containers
    , errors
    , hedgehog-quickcheck ^>=0.1
    , http-media ^>=0.8
    , marlowe-binaries
    , marlowe-plutus
    , marlowe-plutus:marlowe-testing
    , marlowe-transactions
    -- , marlowe-cardano ==0.2.1.0
    -- , marlowe-chain-sync:gen ==1.0.0
    -- , marlowe-chain-sync:plutus-compat
    -- , marlowe-protocols ==0.3.0.0
    -- , marlowe-runtime ==1.0.0
    -- , marlowe-runtime:sync-api
    -- , marlowe-runtime:tx-api
    -- , marlowe-test ==0.2.1.0
    , network-uri >=2.6 && <3
    , nonempty-containers ^>=0.3.4
    , ouroboros-consensus
    , QuickCheck >=2.14 && <3
    , quickcheck-instances ^>=0.3.29
    , sop-core
    , sop-extras
    , strict-sop-core
    , text
    , time


test-suite test
  import:          lang
  type:           exitcode-stdio-1.0
  main-is:        Spec.hs
  hs-source-dirs:  test
  other-modules:
    Language.Marlowe.Runtime.Transaction.BuildConstraintsSpec
    Language.Marlowe.Runtime.Transaction.BuildConstraintsSpec.PropertyBased
  build-depends:
    , aeson
    , aeson-pretty
    , base
    , bytestring
    , cardano-api
    , cardano-crypto-class
    , cardano-debug
    , cardano-ledger-core
    , cardano-slotting
    , convex-mockchain
    , containers
    , deepseq
    , hspec
    , hspec-core
    , marlowe-binaries
    , marlowe-plutus
    , marlowe-plutus:marlowe-testing
    , marlowe-transactions
    , marlowe-transactions:gen
    , nonempty-containers
    , ouroboros-consensus
    , ouroboros-network-api
    , plutus-ledger-api
    , plutus-tx
    , QuickCheck
    , quickcheck-instances
    , sop-core
    , sop-extras
    , strict-sop-core
    , text
    , time
    , transformers
    , vary

executable marlowe-transactions-cli
  import:          lang
  hs-source-dirs:  app
  main-is:         App.hs
  ghc-options:
    -threaded -j8
  other-modules:
    Paths_marlowe_transactions
    Commands
    Commands.Init
    Options
  build-depends:
    , aeson
    , aeson-pretty
    , async-components
    , base
    , base16-bytestring
    , binary
    , bytestring
    , cardano-api
    , cardano-crypto-class
    , cardano-ledger-alonzo
    , cardano-ledger-api
    , cardano-ledger-binary
    , cardano-ledger-core
    , case-insensitive
    , co-log
    , containers
    , deepseq
    , errors
    , exceptions
    , foldl
    , hashable
    , hasql
    , hasql-dynamic-syntax
    , hasql-implicits
    , hasql-pool
    , hasql-th >=0.5
    , hasql-transaction
    , http-conduit
    , http-media
    , http-types
    , insert-ordered-containers
    , lens
    , lifted-base
    , log-base
    , log-base-inlined
    , marlowe-binaries
    , marlowe-object
    , marlowe-plutus ^>=0.2
    , marlowe-transactions
    , monad-control ^>=1
    , mtl
    , network-uri
    , nonempty-containers
    , optparse-applicative
    , openapi3 >=3.2 && <4
    , ouroboros-consensus
    , ouroboros-network-api
    , parsec
    , pipes
    , plutus-core ^>=1.57
    , plutus-ledger-api ^>=1.57
    , plutus-tx ^>=1.57
    , postgresql-syntax
    , profunctors
    , scientific
    , semialign
    , semigroups
    , servant ^>=0.20
    , servant-client ^>=0.20
    , servant-client-core ^>=0.20
    , servant-openapi3 ^>=2.0
    , servant-pagination >=2.5 && <3
    , servant-pipes ^>=0.16
    , servant-server ^>=0.20
    , template-haskell
    , text
    , time
    , transformers
    , transformers-base
    , unliftio-core
    , unordered-containers
    , wai
    , wai-cors
    , wai-extra
    , wai-logger
    , warp
    , witherable
    , variations
    , vector
    , yaml
