cabal-version: 3.4
name:          marlowe-transactions
version:       0.1.0.0
license:       Apache-2.0
build-type:    Simple
maintainer:    tomasz.rybarczyk@marlowe-lang.org
stability:     experimental
author:        paluh (aka Tomasz Rybarczyk)
synopsis:      Marlowe pure transaction builders
category:      Language
license-files:
  LICENSE
  NOTICE

source-repository head
  type:     git
  location: https://github.com/marlowe-lang/marlowe-plutus

common lang
  default-language:   Haskell2010
  default-extensions:
    BangPatterns
    BlockArguments
    ConstraintKinds
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveDataTypeable
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveLift
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    DoAndIfThenElse
    ExplicitForAll
    FlexibleContexts
    FlexibleInstances
    GeneralizedNewtypeDeriving
    ImportQualifiedPost
    LambdaCase
    MultiParamTypeClasses
    NamedFieldPuns
    NumericUnderscores
    OverloadedStrings
    PatternSynonyms
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeOperators
    ViewPatterns

  ghc-options:
    -Wall -Wnoncanonical-monad-instances
    -Wincomplete-uni-patterns -Wincomplete-record-updates
    -Wredundant-constraints -Widentities -Werror

library
  import:          lang
  hs-source-dirs:  src
  build-depends:
    , aeson
    , base
    , bytestring
    , cardano-api
    , cardano-crypto-class
    , cardano-ledger-alonzo
    , cardano-ledger-api
    , cardano-ledger-core
    , containers
    , deepseq
    , errors
    , hashable
    , lens
    , marlowe-binaries ^>=0.2
    , marlowe-plutus ^>=0.2
    , network-uri
    , nonempty-containers
    , ouroboros-consensus
    , ouroboros-network-api
    , plutus-core ^>=1.57
    , plutus-ledger-api ^>=1.57
    , plutus-tx ^>=1.57
    , plutus-tx-plugin ^>=1.57
    , scientific
    , semialign
    , semigroups
    , sop-extras
    , text
    , time
    , transformers
    , unordered-containers
    , vector

  exposed-modules:
    Marlowe.Plutus.Transactions
    Language.Marlowe.Runtime.Cardano.Api
    Language.Marlowe.Runtime.ChainSync.Api
    Language.Marlowe.Runtime.Core.Api
    Language.Marlowe.Runtime.Core.ScriptRegistry
    Language.Marlowe.Runtime.Plutus.V2.Api
    Language.Marlowe.Runtime.Transaction.Api
    Language.Marlowe.Runtime.Transaction.BuildConstraints
    Language.Marlowe.Runtime.Transaction.Constraints

test-suite test
  import:          lang
  type:           exitcode-stdio-1.0
  main-is:        Spec.hs
  hs-source-dirs:  test
  other-modules:
    Language.Marlowe.Runtime.Transaction.BuildConstraintsSpec
  build-depends:
    , base
    , bytestring
    , cardano-api
    , cardano-crypto-class
    , containers
    , deepseq
    , hspec
    , marlowe-plutus
    , marlowe-transactions
    , nonempty-containers
    , ouroboros-consensus
    , plutus-ledger-api
    , plutus-tx
    , QuickCheck
    , quickcheck-instances
    , text
    , time
    , transformers

