cabal-version: 3.4
name:          marlowe-contract-store
version:       0.1.0.0
license:       Apache-2.0
build-type:    Simple
maintainer:    marlowe@marlowe-lang.org
stability:     experimental
author:        Marlowe Team
synopsis:      Marlowe Contract Store which supports merkleization
category:      Language

common lang
  default-language:   Haskell2010
  default-extensions:
    BangPatterns
    BlockArguments
    ConstraintKinds
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveDataTypeable
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveLift
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    DoAndIfThenElse
    DuplicateRecordFields
    ExplicitForAll
    FlexibleContexts
    FlexibleInstances
    GADTs
    GeneralizedNewtypeDeriving
    ImportQualifiedPost
    KindSignatures
    LambdaCase
    MultiParamTypeClasses
    NamedFieldPuns
    NumericUnderscores
    OverloadedStrings
    OverloadedRecordDot
    PatternSynonyms
    PolyKinds
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeOperators
    ViewPatterns

  ghc-options:
    -Wall -Wnoncanonical-monad-instances
    -Wincomplete-uni-patterns -Wincomplete-record-updates
    -Wredundant-constraints -Widentities -Werror
    -threaded

library api
  import:          lang
  hs-source-dirs:  api
  visibility:      public

  build-depends:
    , aeson
    , base >=4.9 && <5
    , binary
    , bytestring
    , containers
    , marlowe-object
    , marlowe-plutus
    , marlowe-transactions
    , singletons
    , text
    , typed-protocols ^>=1.2.0.0
    , variations

  exposed-modules:
    Marlowe.ContractStore.Protocol.Codec
    Marlowe.ContractStore.Protocol.Load.Client
    Marlowe.ContractStore.Protocol.Load.Server
    Marlowe.ContractStore.Protocol.Load.Types
    Marlowe.ContractStore.Protocol.Transfer.Client
    Marlowe.ContractStore.Protocol.Transfer.Server
    Marlowe.ContractStore.Protocol.Transfer.Types

