cabal-version: 3.4
name:          marlowe-indexer
version:       0.1.0.0
license:       Apache-2.0
build-type:    Simple
maintainer:    marlowe@marlowe-lang.org
stability:     experimental
author:        Marlowe Team
synopsis:      Marlowe Runtime Indexer Database Layer
category:      Language

common lang
  default-language:   Haskell2010
  default-extensions:
    BangPatterns
    BlockArguments
    ConstraintKinds
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveDataTypeable
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveLift
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    DoAndIfThenElse
    DuplicateRecordFields
    ExplicitForAll
    FlexibleContexts
    FlexibleInstances
    GeneralizedNewtypeDeriving
    ImportQualifiedPost
    LambdaCase
    MultiParamTypeClasses
    NamedFieldPuns
    NumericUnderscores
    OverloadedStrings
    OverloadedRecordDot
    PatternSynonyms
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeOperators
    ViewPatterns

  ghc-options:
    -Wall -Wnoncanonical-monad-instances
    -Wincomplete-uni-patterns -Wincomplete-record-updates
    -Wredundant-constraints -Widentities -Werror

library
  import:          lang
  hs-source-dirs:  .
  build-depends:
    , base >=4.9 && <5
    , binary
    , bytestring
    , containers
    , hasql
    , hasql-th >=0.5
    , hasql-transaction
    , text
    , time
    , vector
    , marlowe-plutus

  exposed-modules:
    Language.Marlowe.Runtime.ChainSync.Api
    Language.Marlowe.Runtime.Core.Api
    Language.Marlowe.Runtime.History.Api
    Language.Marlowe.Runtime.Indexer.Database.PostgreSQL.CommitBlocks
    Language.Marlowe.Runtime.Indexer.Database.PostgreSQL.CommitRollback
    Language.Marlowe.Runtime.Indexer.Database.PostgreSQL.GetIntersectionPoints
    Language.Marlowe.Runtime.Indexer.Database.PostgreSQL.GetMarloweUTxO
    Language.Marlowe.Runtime.Indexer.Party
    Language.Marlowe.Runtime.Indexer.Types

test-suite marlowe-indexer-test
  import:          lang
  type:            exitcode-stdio-1.0
  hs-source-dirs:  test
  main-is:         Main.hs
  other-modules:   Test
  build-depends:
    , base >=4.9 && <5
    , bytestring
    , containers
    , hasql
    , hasql-th >=0.5
    , hasql-transaction
    , HUnit
    , text
    , time
    , marlowe-indexer
    , temporary
    , transformers

