cabal-version: 3.4
name:          marlowe-plutus
version:       0.2.0.0
license:       Apache-2.0
build-type:    Simple
maintainer:    tomasz.rybarczyk@marlowe-lang.org
stability:     experimental
author:        Alexander Nemish, Brian Bush, Tomasz Rybarczyk, Pablo Lamela
synopsis:      Current reference implementation of Marlowe in Plinth
category:      Language
license-files:
  LICENSE
  NOTICE

data-files:
  benchmarks/rolepayout/*.benchmark
  benchmarks/semantics/*.benchmark

  marlowe-testing/reference/data/*.contract
  marlowe-testing/reference/data/*.paths
  marlowe-testing/data/mainnet-protocol-params.json

  test/contract.json
  test/input.json
  test/Spec/Marlowe/Serialization/golden/swap-contract.json
  test/Spec/Marlowe/Serialization/golden/swap-module.json
  test/state.json

source-repository head
  type:     git
  location: https://github.com/input-output-hk/marlowe-plutus

flag defer-plugin-errors
  description:
    Defer errors from the plugin, useful for things like Haddock that can't handle it.

  default:     False
  manual:      True

flag profile-plutus
  description: Enable Plutus profiling for Marlowe validators.
  default:     False
  manual:      True

flag asdata-case
  description: Use `PlutusTx.asData` for `Case`.
  default:     True
  manual:      True

common lang
  default-language:   Haskell2010
  default-extensions:
    BangPatterns
    BlockArguments
    ConstraintKinds
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveDataTypeable
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveLift
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    DoAndIfThenElse
    DuplicateRecordFields
    ExplicitForAll
    FlexibleContexts
    FlexibleInstances
    GeneralizedNewtypeDeriving
    ImportQualifiedPost
    LambdaCase
    MultiParamTypeClasses
    NamedFieldPuns
    NumericUnderscores
    OverloadedStrings
    OverloadedRecordDot
    PatternSynonyms
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeOperators
    ViewPatterns

  ghc-options:
    -Wall -Wnoncanonical-monad-instances
    -Wincomplete-uni-patterns -Wincomplete-record-updates
    -Wredundant-constraints -Widentities -Werror

  if flag(profile-plutus)
    ghc-options: -fplugin-opt PlutusTx.Plugin:conservative-optimisation

  if flag(profile-plutus)
    ghc-options: -fplugin-opt PlutusTx.Plugin:profile-all

library
  import:          lang
  hs-source-dirs:  src
  build-depends:
    , aeson
    , base >=4.9 && <5
    , bech32 >=1.1 && <2
    , base16-aeson ==0.1.0.0
    , base16-bytestring
    , bytestring
    -- FIXME: We should drop this dependency by:
    -- * Providing our own implementation of plutus data serialization (even if it is a copy)
    -- * Moving this dependency to the test suite only
    -- * Testing that our implementation is compatible with cardano-api's one
    , cardano-api ^>=10.16
    , cardano-crypto-class
    , containers
    , deepseq
    , deriving-aeson
    , flat
    , ilist ==0.4.0.1
    , lens
    , mtl ^>=2.3.1
    , multiplate ==0.0.3
    , newtype-generics
    , plutus-core ==1.45.0.0
    , plutus-ledger-api ==1.45.0.0
    , plutus-tx ==1.45.0.0
    , profunctors >=5.6.3
    , range ==0.3.0.2
    , scientific
    , serialise
    , sbv
    , template-haskell
    , text
    , time ^>= 1.12.2
    , transformers ^>=0.6.1
    , wl-pprint >=1.2 && <2
    , either ^>=5.0.3

  exposed-modules:
    Paths_marlowe_plutus

    Language.Marlowe.Analysis.FSSemantics
    Language.Marlowe.Analysis.Safety.Ledger
    Language.Marlowe.Analysis.Safety.Ledger.Validators
    Language.Marlowe.Analysis.Safety.Transaction
    Language.Marlowe.Analysis.Safety.Types
    Language.Marlowe.Analysis.Safety.Types.Validator
    -- marlowe-plutus is a baseline lib for all the other libs
    -- All the other libs extras are kept here for simplicity.
    Language.Marlowe.Contrib.Data.Foldable
    Language.Marlowe.Contrib.PlutusTx.Debugging.Trace
    Language.Marlowe.Contrib.PlutusTx.Dict
    Language.Marlowe.Contrib.PlutusTx.KeyHashedDict
    Language.Marlowe.Plutus
    Language.Marlowe.Plutus.AssocMap
    Language.Marlowe.Plutus.FindInputs
    Language.Marlowe.Plutus.Foldings
    Language.Marlowe.Plutus.Merkle
    Language.Marlowe.Plutus.Next
    Language.Marlowe.Plutus.Next.Applicables
    Language.Marlowe.Plutus.Next.Applicables.Bound
    Language.Marlowe.Plutus.Next.Applicables.CanChoose
    Language.Marlowe.Plutus.Next.Applicables.CanDeposit
    Language.Marlowe.Plutus.Next.Applicables.CanNotify
    Language.Marlowe.Plutus.Next.CanReduce
    Language.Marlowe.Plutus.Next.Indexed
    Language.Marlowe.Plutus.Next.IsMerkleizedContinuation
    Language.Marlowe.Plutus.OpenRoles
    Language.Marlowe.Plutus.Plate
    Language.Marlowe.Plutus.Pretty
    Language.Marlowe.Plutus.RolePayout
    Language.Marlowe.Plutus.RoleTokens
    Language.Marlowe.Plutus.RoleTokens.Types
    Language.Marlowe.Plutus.Scripts
    Language.Marlowe.Plutus.Scripts.Types
    Language.Marlowe.Plutus.Semantics
    Language.Marlowe.Plutus.Semantics.Types
    Language.Marlowe.Plutus.Semantics.Types.Address

  if flag(asdata-case)
    cpp-options: -DASDATA_CASE

-- Golden tests, fixtures, generators
library marlowe-testing
  import:             lang
  hs-source-dirs:     marlowe-testing
  visibility:        public
  other-modules:
    Paths_marlowe_plutus
  exposed-modules:
    Data.Jsonable
    Marlowe.Testing.ProtocolParams
    Marlowe.Testing.Common
    Marlowe.Testing.Contrib.Integer.Arbitrary
    Marlowe.Testing.Contrib.Data.Functor
    Marlowe.Testing.Contrib.PlutusTx.Arbitrary
    Marlowe.Testing.Contrib.PlutusTx.Debugging.Aeson
    Marlowe.Testing.Contrib.PlutusTx.Lens
    Marlowe.Testing.Contrib.PlutusTx.PlutusTransaction
    Marlowe.Testing.Reference
    Marlowe.Testing.Scripts
    Marlowe.Testing.Semantics.Arbitrary
    Marlowe.Testing.Semantics.AssocMap
    Marlowe.Testing.Semantics.Golden
    Marlowe.Testing.Semantics.Golden.Escrow
    Marlowe.Testing.Semantics.Golden.Negative
    Marlowe.Testing.Semantics.Golden.Pangram
    Marlowe.Testing.Semantics.Golden.Swap
    Marlowe.Testing.Semantics.Golden.Trivial
    Marlowe.Testing.Semantics.Golden.ZeroCouponBond
    Marlowe.Testing.Semantics.Next.Arbitrary
    Marlowe.Testing.Semantics.Path
    Marlowe.Testing.Semantics.Util
    Marlowe.Testing.Service
    Marlowe.Testing.Service.Random
    Marlowe.Testing.Service.Serialization
    Marlowe.Testing.Service.Types
    Marlowe.Testing.Transactions

  build-depends:
    , aeson
    , aeson-pretty
    , base >=4.9 && <5
    , base16-aeson ==0.1.0.0
    , base16-bytestring
    , bytestring
    , cardano-api ^>=10.16
    , cardano-crypto-class
    , containers ^>=0.6.5
    , data-default
    , directory ^>=1.3
    , filepath ^>=1.4
    , hspec
    , hspec-core
    , lens
    , marlowe-plutus:{marlowe-plutus}
    , mtl >=2.2 && <3
    , QuickCheck >=2.14 && <3
    , plutus-core ==1.45.0.0
    , plutus-ledger-api ==1.45.0.0
    , plutus-tx
    , serialise
    , tasty-quickcheck ^>=0.11
    , text
    , transformers
    , vector
    , yaml

  build-tool-depends: hspec-discover:hspec-discover
  ghc-options:        -threaded

executable marlowe-testing-reference
  import:         lang
  hs-source-dirs: marlowe-testing/reference
  main-is:        Main.hs
  build-depends:
    , base >=4.9 && <5
    , directory
    , filepath
    , marlowe-plutus:{marlowe-testing}
    , mtl >=2.2 && <3

-- The core spec for the interpreter
test-suite marlowe-plutus-test
  import:         lang
  hs-source-dirs: test
  main-is:        Spec.hs
  type:               exitcode-stdio-1.0
  other-modules:
    Paths_marlowe_plutus
    Spec.PlutusTx
    Spec.PlutusTx.AssocMap
    Spec.PlutusTx.MList
    Spec.PlutusTx.Prelude
    Spec.PlutusTx.ScriptContext
    Spec.PlutusTx.Specification
    Spec.PlutusTx.Value
    Spec.Marlowe.Marlowe
    Spec.Marlowe.Plate
    Spec.Marlowe.Semantics
    Spec.Marlowe.Semantics.Compute
    Spec.Marlowe.Semantics.Entropy
    Spec.Marlowe.Semantics.Functions
    Spec.Marlowe.Semantics.Golden.Tests
    Spec.Marlowe.Semantics.Next
    Spec.Marlowe.Semantics.Next.Common.Isomorphism
    Spec.Marlowe.Semantics.Next.Common.QuickCheck
    Spec.Marlowe.Semantics.Next.Common.Tuple
    Spec.Marlowe.Semantics.Next.Contract
    Spec.Marlowe.Semantics.Next.Contract.Generator
    Spec.Marlowe.Semantics.Next.Contract.When
    Spec.Marlowe.Semantics.Next.Contract.When.Choice
    Spec.Marlowe.Semantics.Next.Contract.When.Deposit
    Spec.Marlowe.Semantics.Next.Contract.When.Notify
    Spec.Marlowe.Semantics.Path.Tests
    Spec.Marlowe.Serialization
    Spec.Marlowe.Service.Isabelle
    Spec.Marlowe.StaticAnalysis
    Spec.Marlowe.StaticAnalysis.Regression

  build-depends:
    , aeson
    , base >=4.9 && <5
    , bytestring
    , cardano-api
    , containers ^>=0.6.5
    , data-default
    , filepath ^>=1.4
    , hint ^>=0.9
    , hspec
    , ilist ==0.4.0.1
    , lens >=5.2 && <6
    , marlowe-plutus:{marlowe-plutus, marlowe-testing}
    , marlowe-spec-test ==0.1.0.2
    , mtl >=2.2 && <3
    , plutus-ledger-api ==1.45.0.0
    , plutus-tx ==1.45.0.0
    , QuickCheck >=2.14 && <3
    , quickcheck-instances ^>=0.3.29
    , sbv
    , tasty ^>=1.5
    , tasty-hspec
    , tasty-hunit ^>=0.10
    , tasty-quickcheck ^>=0.11
    , text
    , type-iso ==1.0.1.0

