cabal-version: 3.4
name:          cardano-debug
version:       0.0.1
license:       Apache-2.0
license-files:
  LICENSE
  NOTICE

build-type:    Simple
maintainer:    tomasz.rybarczyk@marlowe-lang.org
stability:     stable
synopsis:      Debugging helpers extracted from cardano-cli

source-repository head
  type:     git
  location: https://github.com/marlowe-lang/marlowe-plutus
  subdir:   libs/cardano-debug

flag defer-plugin-errors
  description:
    Defer errors from the plugin, useful for things like Haddock that can't handle it.

  default:     False
  manual:      True

common lang
  default-language:   Haskell2010
  default-extensions:
    BangPatterns
    BlockArguments
    ConstraintKinds
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveDataTypeable
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveLift
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    DoAndIfThenElse
    ExplicitForAll
    FlexibleContexts
    FlexibleInstances
    GADTs
    GeneralizedNewtypeDeriving
    ImportQualifiedPost
    LambdaCase
    MultiParamTypeClasses
    NamedFieldPuns
    NumericUnderscores
    OverloadedStrings
    PatternSynonyms
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeOperators
    ViewPatterns

  ghc-options:
    -Wall -Wnoncanonical-monad-instances -Wunused-packages
    -Wincomplete-uni-patterns -Wincomplete-record-updates
    -Wredundant-constraints -Widentities

  if flag(defer-plugin-errors)
    ghc-options: -fplugin-opt PlutusTx.Plugin:defer-errors

  default-extensions:
    DataKinds
    ImportQualifiedPost

library
  import:          lang
  hs-source-dirs:  src
  exposed-modules:
    Cardano.Debug

  -- Those two are re-exported
  other-modules:
    Cardano.Debug.Json
    Cardano.Debug.MonadWarning

  build-depends:
    , aeson
    , aeson-pretty
    , base >=4.9 && <5
    , bytestring
    , cardano-api ^>=10.23
    , cardano-crypto-class
    , cardano-ledger-core
    , containers
    , microlens
    , mtl
    , text
    , transformers
    , vary
    , vector
    , yaml
