{
  lib,
  postgresql,
  coreutils,
  writeText,
  writeShellApplication,
  sqitchPg,
}:
let
  validate-postgres-env = writeShellApplication {
    name = "validate-postgres-env";
    runtimeInputs = [coreutils];
    # Check if all variables are defined and if not stop the process.
    text = ''
      set -euo pipefail
      set -x

      : "''${SQITCH_CHDIR:?}"
      : "''${POSTGRES_DIR:?}"
      : "''${PGPORT:?}"
    '';
  };
  clear-postgres-state = writeShellApplication {
    name = "clear-postgres-state";
    runtimeInputs = [coreutils];
    text = ''
      set -x
      if [ -d "$POSTGRES_DIR" ]; then
        rm -rf "$POSTGRES_DIR"
      fi;
      mkdir -p "$POSTGRES_DIR"
    '';
  };
  setup-postgres = let
    hbaConf = [
      {
        type = "local";
        database = "all";
        user = "all";
        address = "";
        method = "trust";
      }
      {
        type = "host";
        database = "all";
        user = "all";
        address = "127.0.0.1/32";
        method = "trust";
      }
      {
        type = "host";
        database = "all";
        user = "all";
        address = "::1/128";
        method = "trust";
      }
      {
        type = "local";
        database = "replication";
        user = "all";
        address = "";
        method = "trust";
      }
      {
        type = "host";
        database = "replication";
        user = "all";
        address = "127.0.0.1/32";
        method = "trust";
      }
      {
        type = "host";
        database = "replication";
        user = "all";
        address = "::1/128";
        method = "trust";
      }
    ];
    hbaConfString = ''
      # Generated by Nix
      ${"# TYPE\tDATABASE\tUSER\tADDRESS\tMETHOD\n"}
      ${lib.concatMapStrings (cnf: "  ${cnf.type}\t${cnf.database}\t${cnf.user}\t${cnf.address}\t${cnf.method}\n") hbaConf}
    '';
    hbaFile = writeText "pg_hba.conf" hbaConfString;
    pgConfig = {
      listen_addresses = "127.0.0.1";
      port = 15432;
      hba_file = "${hbaFile}";
    };
    toStr = value:
      if true == value
      then "yes"
      else if false == value
      then "no"
      else if lib.isString value
      then "'${lib.replaceStrings ["'"] ["''"] value}'"
      else toString value;
    configFile =
      writeText "postgresql.conf" (lib.concatStringsSep "\n"
        (lib.mapAttrsToList (n: v: "${n} = ${toStr v}") pgConfig));
  in
    writeShellApplication {
      name = "setup-postgres";
      runtimeInputs = [postgresql coreutils];
      text = ''
        set -x

        export PGDATA="$POSTGRES_DIR/pgdata"

        function psql_with_args() {
          psql -v "ON_ERROR_STOP=1" "$@"
        }
        POSTGRES_RUN_INITIAL_SCRIPT="false"
        if [[ ! -d "$PGDATA" ]]; then
          initdb -D "$PGDATA"
          POSTGRES_RUN_INITIAL_SCRIPT="true"
          echo
          echo "PostgreSQL initdb process complete."
          echo
        fi
        echo "Setting up postgresql.conf"
        cp ${configFile} "$PGDATA/postgresql.conf"
        sed -i "s/${toString pgConfig.port}/''${PGPORT}/" "$PGDATA/postgresql.conf"
        if [[ "$POSTGRES_RUN_INITIAL_SCRIPT" = "true" ]]; then
          echo
          echo "PostgreSQL is setting up the initial database."
          echo
          PGHOST="$(mktemp -d /tmp/pg-init-XXXXXX)"
          export PGHOST
          function remove_tmp_pg_init_sock_dir() {
            if [[ -d "$1" ]]; then
              rm -rf "$1"
            fi
          }
          trap 'remove_tmp_pg_init_sock_dir "$PGHOST"' EXIT
          pg_ctl -D "$PGDATA" -w start -o "-c unix_socket_directories=$PGHOST -c listen_addresses= -p $PGPORT"
          echo "CREATE DATABASE marlowe;" | psql_with_args -d postgres
          echo "CREATE USER marlowe;" | psql_with_args -d postgres
          echo "ALTER DATABASE marlowe OWNER TO marlowe;" | psql_with_args -d postgres
          pg_ctl -D "$PGDATA" -m fast -w stop
          remove_tmp_pg_init_sock_dir "$PGHOST"
        else
          echo
          echo "PostgreSQL database directory appears to contain a database; Skipping initialization"
          echo
        fi
        unset POSTGRES_RUN_INITIAL_SCRIPT
      '';
    };

  postgres-server = writeShellApplication {
    name = "postgres-server";
    runtimeInputs = [postgresql coreutils];
    text = ''
      set -x

      export PGDATA="$POSTGRES_DIR/pgdata"
      postgres -D "$PGDATA" -k "$PGDATA"
    '';
  };

  initialize-postgres = writeShellApplication {
    name = "initialize-postgres";
    runtimeInputs = [sqitchPg];
    text = ''
      set -x
      export PGDATA="$POSTGRES_DIR/pgdata"
      sqitch rebase db:pg://marlowe@localhost/marlowe --chdir "$SQITCH_CHDIR" || sqitch deploy db:pg://marlowe@localhost/marlowe --chdir "$SQITCH_CHDIR"
    '';
  };

  postgres-ready = writeShellApplication {
    name = "postgres-ready";
    runtimeInputs = [postgresql];
    text = ''
      set -x
      export PGDATA="$POSTGRES_DIR/pgdata"
      pg_isready -h localhost -d marlowe
    '';
  };
in {
  "clear-postgres-state" = {
    namespace = "marlowe@postgres";
    command = "${clear-postgres-state}/bin/clear-postgres-state";
  };
  "postgres-init" = {
    namespace = "marlowe@postgres";
    log_location = "$POSTGRES_DIR/postgres-init.log";
    depends_on = {
      "clear-postgres-state" = {
        condition = "process_completed_successfully";
      };
    };
    command = "${setup-postgres}/bin/setup-postgres";
  };
  "postgres-server" = {
    namespace = "marlowe@postgres";
    log_location = "$POSTGRES_DIR/postgres.log";
    depends_on = {
      "postgres-init" = {
        condition = "process_completed_successfully";
      };
    };
    command = "${postgres-server}/bin/postgres-server";
    shutdown = {
      signal = 2;
    };
    availability = {
      restart = "on_failure";
      max_restarts = 5;
    };
    readiness_probe = {
      exec = {
        command = "${postgres-ready}/bin/postgres-ready";
      };
      initial_delay_seconds = 2;
      period_seconds = 1;
      timeout_seconds = 4;
      success_threshold = 1;
      failure_threshold = 5;
    };
  };
  "initialize-postgres" = {
    namespace = "marlowe@postgres";
    command = "${initialize-postgres}/bin/initialize-postgres";
    depends_on = {
      "postgres-server" = {
        condition = "process_healthy";
      };
    };
  };
}
